server:
  port: 9000
spring:
  application:
    name: commodity
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${database.host}:3306/${spring.application.name}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${database.username}
    password: ${database.password}
  main:
    banner-mode: off

# mp
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
    banner: false
# 日志
logging:
  level:
    io.github.caolib: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
# API文档
knife4j:
  enable: true
  openapi:
    title: ikun-shop API
    description: "ikun shop 商品接口文档"
    email: 1265501579@qq.com
    concat: caolib
    url: https://github.com/caolib
    version: v0.0.1
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - io.github.caolib.controller