server:
  port: 8080
spring:
  cloud:
    gateway:
      # 路由规则
      routes:
        - id: cart
          uri: lb://cart
          predicates:
            - Path=/carts/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/orders/**
        - id: user
          uri: lb://user
          predicates:
            - Path=/users/**,/addresses/**,/oauth/**
          filters:
            - AddRequestHeader=X-Request-red, blue
        - id: commodity
          uri: lb://commodity
          predicates:
            - Path=/commodity/**,/search/**
        - id: pay
          uri: lb://pay
          predicates:
            - Path=/pays/**
      default-filters:
        - AddRequestHeader=X-Request-red, blue
  main:
    banner-mode: off

# 校验信息
shop:
  jwt:
    location: classpath:key.jks
    alias: ikun
    password: ikun-shop-123456
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /oauth/**
      - /items/**
      - /hi
