spring:
  redis:
    host: centos
    port: 6379
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 1000ms
    database: 2
  cache:
    redis:
      time-to-live: 600000 # 缓存过期时间