server:
  port: 443
  address: "::"
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ikun666
    key-store-type: PKCS12
    key-alias: ikun-shop
spring:
  main:
    banner-mode: off # 关闭启动时的logo
  output:
    ansi:
      enabled: always
shop:
  # 密钥校验信息
  jwt:
    location: classpath:key.jks
    alias: ikun
    password: ikun-shop-123456
  auth:
    # 无需校验身份的路径
    excludePaths:
      - /**/login
      - /**/register
      - /oauth/**
      - /**/health
      - /commodity/home
