server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      # 路由规则
      routes:
        - id: cart
          uri: lb://cart
          predicates:
            - Path=/carts/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/orders/**
        - id: user
          uri: lb://user
          predicates:
            - Path=/users/**,/addresses/**,/oauth/**
          filters:
            - AddRequestHeader=X-Request-red, blue
        - id: commodity
          uri: lb://commodity
          predicates:
            - Path=/commodity/**,/search/**
        - id: pay
          uri: lb://pay
          predicates:
            - Path=/pays/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://shop-clb.pages.dev/"
              - "https://shop.caolib.us.kg"
              - "http://localhost:5173"
              - "http://localhost:18080"
              - http://localhost:1420
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

  main:
    banner-mode: off
  # 禁用jmx，防止热重载失败
  devtools:
    jmx:
      enabled: false
# 密钥校验信息
shop:
  jwt:
    location: classpath:key.jks
    alias: ikun
    password: ikun-shop-123456
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /users/register
      - /oauth/**
      - /items/**
      - /**/health

# 健康状态检查
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /gateway/health