server:
  port: 8080
spring:
  main:
    banner-mode: off # 关闭启动时的logo
shop:
  # 密钥校验信息
  jwt:
    location: classpath:key.jks
    alias: ikun
    password: ikun-shop-123456
  auth:
    # 无需校验身份的路径
    excludePaths:
      - /**/login
      - /**/register
      - /oauth/**
      - /**/health
      - /commodity/home

