server:
  port: 9200
spring:
  main:
    banner-mode: off

shop:
  jwt:
    location: classpath:key.jks
    alias: ikun
    password: ikun-shop-123456
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /oauth/**
      - /items/**
      - /hi