spring:
  cloud:
    nacos:
      config:
        server-addr: ${spring.cloud.nacos.server-addr}
        namespace: 1e50c70c-a061-4b57-ade3-58760a65ebc5
        group: DEV
        extension-configs:
          - data-id: user-init.yaml
            refresh: true
  redis:
    database: 2

# mysql
mysql:
  name: user
  host: localhost
  username: root
  password: root


