server:
  port: 9200

shop:
  jwt:
    location: classpath:key.jks
    alias: ikun
    password: ikun-shop-123456
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi