server:
  port: 9200
  address: "::"

spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
shop:
  # jwt令牌校验
  jwt:
    location: classpath:key.jks
    alias: ikun
    password: ikun-shop-123456
  # 路径白名单
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /oauth/**
      - /items/**
      - /hi
# 地址
addr:
  max-count: 10

# mysql
mysql:
  name: user
  host: localhost
  username: root
  password: root

