# mysql
database:
  name: user
  host: localhost
  username: root
  password: root

# redis
redis:
  database: 1

# 健康状态
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /users/health

